import:
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-base-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-r4.0.yml
language: python

jobs:
  include:
    - python: '3.5'
      install: pip install --quiet -r ci/requirements.txt
      env: TESTS_ONLY=1
      script:
       - ./run-tests
       - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
      after_success:
       - codecov
    - stage: deploy
      python: '3.5'
      env: DIST_DOM0=fc25 TESTS_ONLY=
      script: ~/qubes-builder/scripts/travis-deploy
